data_dir: data/processed
tokenizer_path: artifacts/tokenizer
tokenizer_notation_mode: both
tokenizer_path_by_notation:
  english: artifacts/tokenizer_english
  italiano: artifacts/tokenizer_italiano
  both: artifacts/tokenizer
labels_path: data/labels/labels_v1.json
language: english
pretokenized_path: null
